### ISSUE TITLE
Findings are not shown

### ISSUE THREAD

**Issue by janlau1111** [aquasecurity/intellij-tfsec#3]
Hello,
i wanted to try you Tfsec Findings Browser. I installed it to intellij IDEA 2021.2. I can open the view also tfsec is executed and i see findings in the json file which is created by tfsec. In the intellij view i only see the category but no details to the findings.

![image](https://user-images.githubusercontent.com/42604613/158817739-93d9ef7b-2eb6-4f2b-a916-444eb83027c3.png)
![image](https://user-images.githubusercontent.com/42604613/158817891-8c28cc77-3df3-4704-a6d8-35f0571b4367.png)
![image](https://user-images.githubusercontent.com/42604613/158818305-75add7c8-26ed-41a0-815a-830de0eed0c8.png)

**Comment by owenrumney** [comment]
Thanks @janlau1111  - I'll take a look at this asap

**Comment by devsecopshomelearning** [comment]
I believe it has to do with a NullPointerException. I have the same issue inside of PyCharm, when this occurs I have to terminate the program and reopen, and close the tfsec window real fast before the error returns.

`java.lang.NullPointerException
	at com.aquasecurity.plugins.tfsec.model.Findings.setBasePath(Findings.java:19)
	at com.aquasecurity.plugins.tfsec.ui.TfsecWindow.updateFindings(TfsecWindow.java:71)
	at com.aquasecurity.plugins.tfsec.actions.ResultProcessor.updateResults(ResultProcessor.java:35)
	at com.aquasecurity.plugins.tfsec.actions.TfsecBackgroundRunTask.lambda$run$0(TfsecBackgroundRunTask.java:66)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by owenrumney** [comment]
HI @janlau1111  - v1.1.0 is in approval stages with Jetbrains and this will resolve the issue
